import { NextResponse } from 'next/server';
import { sql } from '@vercel/postgres';

export const runtime = 'nodejs';

/**
 * Test the INSERT query to see what's actually being executed
 */
export async function GET() {
  try {
    // Test data similar to what Jikan returns
    const testAnime = {
      mal_id: 99999, // Use a high ID that doesn't exist
      title: 'Test Anime',
      english_title: 'Test Anime English',
      japanese_title: 'テストアニメ',
      synonyms: null,
      description: 'This is a test anime for debugging',
      image_url: 'https://example.com/test.jpg',
      score: null,
      popularity: 9999,
      rank: null,
      rating: 'PG-13',
      status: 'Not yet aired',
      premiered: 'winter 2025',
      demographic: null,
      producers: 'Test Studio',
    };

    console.log('Testing INSERT query with data:', testAnime);

    // First, delete if exists
    await sql`DELETE FROM anime WHERE mal_id = ${testAnime.mal_id}`;

    // Try the same INSERT query as in animeCacheService.ts
    const result = await sql`
      INSERT INTO anime (
        mal_id, title, english_title, japanese_title, synonyms, 
        description, image_url, score, popularity, rank, rating, 
        status, premiered, demographic, producers, 
        last_jikan_sync, sync_status, created_at, updated_at
      )
      VALUES (
        ${testAnime.mal_id}, ${testAnime.title}, ${testAnime.english_title}, ${testAnime.japanese_title}, 
        ${testAnime.synonyms}, ${testAnime.description}, ${testAnime.image_url}, ${testAnime.score}, 
        ${testAnime.popularity}, ${testAnime.rank}, ${testAnime.rating}, ${testAnime.status}, 
        ${testAnime.premiered}, ${testAnime.demographic}, ${testAnime.producers}, 
        NOW(), 'pending_embeddings', NOW(), NOW()
      )
      RETURNING anime_id, mal_id, title, last_jikan_sync, sync_status
    `;

    // Clean up test data
    await sql`DELETE FROM anime WHERE mal_id = ${testAnime.mal_id}`;

    return NextResponse.json({
      success: true,
      message: 'INSERT query works correctly!',
      result: result.rows[0],
      columns_count: 19, // Number of columns in INSERT
      note: 'anime_id was auto-generated by the database',
    });
  } catch (error) {
    console.error('Test INSERT error:', error);
    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
      stack: error instanceof Error ? error.stack : undefined,
    }, { status: 500 });
  }
}
